# Generated by Django 3.0.6 on 2020-06-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='similarity',
            table=None,
        ),
    ]
