# Generated by Django 3.0.6 on 2020-05-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date last modified')),
                ('user', models.CharField(max_length=20)),
                ('contents', models.TextField()),
            ],
        ),
    ]
