# Generated by Django 3.0.5 on 2020-05-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualPlanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='title',
            field=models.CharField(default='새 일정', max_length=30),
        ),
    ]
