# Generated by Django 3.0.5 on 2020-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualPlanner', '0002_planner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='id',
        ),
        migrations.AlterField(
            model_name='planner',
            name='user',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
