# Generated by Django 3.0.5 on 2020-06-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualPlanner', '0004_auto_20200527_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentId', models.CharField(max_length=10)),
                ('contentName', models.CharField(max_length=30)),
                ('contentType', models.CharField(max_length=10)),
                ('userId', models.CharField(max_length=20)),
                ('userType', models.CharField(max_length=10)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
