# Generated by Django 3.0.6 on 2020-06-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualPlanner', '0007_planner_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='userType',
            new_name='userDType',
        ),
        migrations.AddField(
            model_name='rating',
            name='userPType',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
